# Generated by Django 2.0 on 2018-05-02 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('date', 'url'),
            },
        ),
        migrations.CreateModel(
            name='Shorturls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortname', models.SlugField(max_length=100, unique=True)),
                ('url', models.CharField(help_text='The URI to redirect to.', max_length=400)),
            ],
            options={
                'ordering': ('shortname',),
                'verbose_name': 'Short URI',
            },
        ),
        migrations.AddField(
            model_name='hit',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shorturls.Shorturls'),
        ),
    ]
